//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL.AL_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_User", Namespace="http://schemas.datacontract.org/2004/07/AL_SERVICE.DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> _CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> _IsOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _NikeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> _StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> _CreateDate {
            get {
                return this._CreateDateField;
            }
            set {
                if ((this._CreateDateField.Equals(value) != true)) {
                    this._CreateDateField = value;
                    this.RaisePropertyChanged("_CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _ID {
            get {
                return this._IDField;
            }
            set {
                if ((this._IDField.Equals(value) != true)) {
                    this._IDField = value;
                    this.RaisePropertyChanged("_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _IP {
            get {
                return this._IPField;
            }
            set {
                if ((object.ReferenceEquals(this._IPField, value) != true)) {
                    this._IPField = value;
                    this.RaisePropertyChanged("_IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> _IsOk {
            get {
                return this._IsOkField;
            }
            set {
                if ((this._IsOkField.Equals(value) != true)) {
                    this._IsOkField = value;
                    this.RaisePropertyChanged("_IsOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Nike {
            get {
                return this._NikeField;
            }
            set {
                if ((object.ReferenceEquals(this._NikeField, value) != true)) {
                    this._NikeField = value;
                    this.RaisePropertyChanged("_Nike");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Number {
            get {
                return this._NumberField;
            }
            set {
                if ((object.ReferenceEquals(this._NumberField, value) != true)) {
                    this._NumberField = value;
                    this.RaisePropertyChanged("_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Pass {
            get {
                return this._PassField;
            }
            set {
                if ((object.ReferenceEquals(this._PassField, value) != true)) {
                    this._PassField = value;
                    this.RaisePropertyChanged("_Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Remark {
            get {
                return this._RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this._RemarkField, value) != true)) {
                    this._RemarkField = value;
                    this.RaisePropertyChanged("_Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> _State {
            get {
                return this._StateField;
            }
            set {
                if ((this._StateField.Equals(value) != true)) {
                    this._StateField = value;
                    this.RaisePropertyChanged("_State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Login", Namespace="http://schemas.datacontract.org/2004/07/AL_SERVICE.DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginMessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AL.AL_Service.DTO_Friend[] MyFriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AL.AL_Service.GroupInfo[] MyGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AL.AL_Service.UserInfo MyMessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLogin {
            get {
                return this.IsLoginField;
            }
            set {
                if ((this.IsLoginField.Equals(value) != true)) {
                    this.IsLoginField = value;
                    this.RaisePropertyChanged("IsLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginMess {
            get {
                return this.LoginMessField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginMessField, value) != true)) {
                    this.LoginMessField = value;
                    this.RaisePropertyChanged("LoginMess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AL.AL_Service.DTO_Friend[] MyFriends {
            get {
                return this.MyFriendsField;
            }
            set {
                if ((object.ReferenceEquals(this.MyFriendsField, value) != true)) {
                    this.MyFriendsField = value;
                    this.RaisePropertyChanged("MyFriends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AL.AL_Service.GroupInfo[] MyGroup {
            get {
                return this.MyGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.MyGroupField, value) != true)) {
                    this.MyGroupField = value;
                    this.RaisePropertyChanged("MyGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AL.AL_Service.UserInfo MyMess {
            get {
                return this.MyMessField;
            }
            set {
                if ((object.ReferenceEquals(this.MyMessField, value) != true)) {
                    this.MyMessField = value;
                    this.RaisePropertyChanged("MyMess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/AL_SERVICE")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UI_CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UI_HeadImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UI_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UI_IsOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UI_IsVipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UI_NikeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UI_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UI_PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UI_RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UI_SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UI_StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UI_CreateDate {
            get {
                return this.UI_CreateDateField;
            }
            set {
                if ((this.UI_CreateDateField.Equals(value) != true)) {
                    this.UI_CreateDateField = value;
                    this.RaisePropertyChanged("UI_CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UI_HeadImg {
            get {
                return this.UI_HeadImgField;
            }
            set {
                if ((object.ReferenceEquals(this.UI_HeadImgField, value) != true)) {
                    this.UI_HeadImgField = value;
                    this.RaisePropertyChanged("UI_HeadImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UI_ID {
            get {
                return this.UI_IDField;
            }
            set {
                if ((this.UI_IDField.Equals(value) != true)) {
                    this.UI_IDField = value;
                    this.RaisePropertyChanged("UI_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UI_IsOk {
            get {
                return this.UI_IsOkField;
            }
            set {
                if ((this.UI_IsOkField.Equals(value) != true)) {
                    this.UI_IsOkField = value;
                    this.RaisePropertyChanged("UI_IsOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UI_IsVip {
            get {
                return this.UI_IsVipField;
            }
            set {
                if ((this.UI_IsVipField.Equals(value) != true)) {
                    this.UI_IsVipField = value;
                    this.RaisePropertyChanged("UI_IsVip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UI_Nike {
            get {
                return this.UI_NikeField;
            }
            set {
                if ((object.ReferenceEquals(this.UI_NikeField, value) != true)) {
                    this.UI_NikeField = value;
                    this.RaisePropertyChanged("UI_Nike");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UI_Number {
            get {
                return this.UI_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.UI_NumberField, value) != true)) {
                    this.UI_NumberField = value;
                    this.RaisePropertyChanged("UI_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UI_Pass {
            get {
                return this.UI_PassField;
            }
            set {
                if ((object.ReferenceEquals(this.UI_PassField, value) != true)) {
                    this.UI_PassField = value;
                    this.RaisePropertyChanged("UI_Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UI_Remark {
            get {
                return this.UI_RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.UI_RemarkField, value) != true)) {
                    this.UI_RemarkField = value;
                    this.RaisePropertyChanged("UI_Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UI_Sex {
            get {
                return this.UI_SexField;
            }
            set {
                if ((this.UI_SexField.Equals(value) != true)) {
                    this.UI_SexField = value;
                    this.RaisePropertyChanged("UI_Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UI_State {
            get {
                return this.UI_StateField;
            }
            set {
                if ((this.UI_StateField.Equals(value) != true)) {
                    this.UI_StateField = value;
                    this.RaisePropertyChanged("UI_State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Friend", Namespace="http://schemas.datacontract.org/2004/07/AL_SERVICE.DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_Friend : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> _GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _NikeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _RemarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> _Group {
            get {
                return this._GroupField;
            }
            set {
                if ((this._GroupField.Equals(value) != true)) {
                    this._GroupField = value;
                    this.RaisePropertyChanged("_Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _ID {
            get {
                return this._IDField;
            }
            set {
                if ((this._IDField.Equals(value) != true)) {
                    this._IDField = value;
                    this.RaisePropertyChanged("_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Nike {
            get {
                return this._NikeField;
            }
            set {
                if ((object.ReferenceEquals(this._NikeField, value) != true)) {
                    this._NikeField = value;
                    this.RaisePropertyChanged("_Nike");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Number {
            get {
                return this._NumberField;
            }
            set {
                if ((object.ReferenceEquals(this._NumberField, value) != true)) {
                    this._NumberField = value;
                    this.RaisePropertyChanged("_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Remark {
            get {
                return this._RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this._RemarkField, value) != true)) {
                    this._RemarkField = value;
                    this.RaisePropertyChanged("_Remark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupInfo", Namespace="http://schemas.datacontract.org/2004/07/AL_SERVICE")]
    [System.SerializableAttribute()]
    public partial class GroupInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> GI_CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GI_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GI_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GI_RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GI_UI_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> GI_CreateDate {
            get {
                return this.GI_CreateDateField;
            }
            set {
                if ((this.GI_CreateDateField.Equals(value) != true)) {
                    this.GI_CreateDateField = value;
                    this.RaisePropertyChanged("GI_CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GI_ID {
            get {
                return this.GI_IDField;
            }
            set {
                if ((this.GI_IDField.Equals(value) != true)) {
                    this.GI_IDField = value;
                    this.RaisePropertyChanged("GI_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GI_Name {
            get {
                return this.GI_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.GI_NameField, value) != true)) {
                    this.GI_NameField = value;
                    this.RaisePropertyChanged("GI_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GI_Remark {
            get {
                return this.GI_RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.GI_RemarkField, value) != true)) {
                    this.GI_RemarkField = value;
                    this.RaisePropertyChanged("GI_Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GI_UI_ID {
            get {
                return this.GI_UI_IDField;
            }
            set {
                if ((this.GI_UI_IDField.Equals(value) != true)) {
                    this.GI_UI_IDField = value;
                    this.RaisePropertyChanged("GI_UI_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_SMess", Namespace="http://schemas.datacontract.org/2004/07/AL_SERVICE.DTO")]
    [System.SerializableAttribute()]
    public partial class DTO_SMess : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AL.AL_Service.UserInfo DespatcherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Furl1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReadTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AL.AL_Service.DTO_Friend SendToNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AL.AL_Service.UserInfo Despatcher {
            get {
                return this.DespatcherField;
            }
            set {
                if ((object.ReferenceEquals(this.DespatcherField, value) != true)) {
                    this.DespatcherField = value;
                    this.RaisePropertyChanged("Despatcher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Furl1 {
            get {
                return this.Furl1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Furl1Field, value) != true)) {
                    this.Furl1Field = value;
                    this.RaisePropertyChanged("Furl1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReadType {
            get {
                return this.ReadTypeField;
            }
            set {
                if ((this.ReadTypeField.Equals(value) != true)) {
                    this.ReadTypeField = value;
                    this.RaisePropertyChanged("ReadType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AL.AL_Service.DTO_Friend SendToNum {
            get {
                return this.SendToNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SendToNumField, value) != true)) {
                    this.SendToNumField = value;
                    this.RaisePropertyChanged("SendToNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AL_Service.IAL_Service", CallbackContract=typeof(AL.AL_Service.IAL_ServiceCallback))]
    public interface IAL_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAL_Service/Login", ReplyAction="http://tempuri.org/IAL_Service/LoginResponse")]
        AL.AL_Service.DTO_Login Login(AL.AL_Service.DTO_User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAL_Service/Login", ReplyAction="http://tempuri.org/IAL_Service/LoginResponse")]
        System.Threading.Tasks.Task<AL.AL_Service.DTO_Login> LoginAsync(AL.AL_Service.DTO_User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAL_Service/SendMessage", ReplyAction="http://tempuri.org/IAL_Service/SendMessageResponse")]
        int SendMessage(AL.AL_Service.DTO_SMess sm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAL_Service/SendMessage", ReplyAction="http://tempuri.org/IAL_Service/SendMessageResponse")]
        System.Threading.Tasks.Task<int> SendMessageAsync(AL.AL_Service.DTO_SMess sm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAL_Service/Register", ReplyAction="http://tempuri.org/IAL_Service/RegisterResponse")]
        void Register(AL.AL_Service.DTO_User _reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAL_Service/Register", ReplyAction="http://tempuri.org/IAL_Service/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(AL.AL_Service.DTO_User _reg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAL_ServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAL_Service/Login_Prompt")]
        void Login_Prompt(string _login);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAL_Service/Message")]
        void Message(AL.AL_Service.DTO_SMess _sm);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAL_Service/LogoutMessa")]
        void LogoutMessa(string _num);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAL_ServiceChannel : AL.AL_Service.IAL_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AL_ServiceClient : System.ServiceModel.DuplexClientBase<AL.AL_Service.IAL_Service>, AL.AL_Service.IAL_Service {
        
        public AL_ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AL_ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AL_ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AL_ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AL_ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public AL.AL_Service.DTO_Login Login(AL.AL_Service.DTO_User u) {
            return base.Channel.Login(u);
        }
        
        public System.Threading.Tasks.Task<AL.AL_Service.DTO_Login> LoginAsync(AL.AL_Service.DTO_User u) {
            return base.Channel.LoginAsync(u);
        }
        
        public int SendMessage(AL.AL_Service.DTO_SMess sm) {
            return base.Channel.SendMessage(sm);
        }
        
        public System.Threading.Tasks.Task<int> SendMessageAsync(AL.AL_Service.DTO_SMess sm) {
            return base.Channel.SendMessageAsync(sm);
        }
        
        public void Register(AL.AL_Service.DTO_User _reg) {
            base.Channel.Register(_reg);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(AL.AL_Service.DTO_User _reg) {
            return base.Channel.RegisterAsync(_reg);
        }
    }
}
